// <auto-generated />
namespace HelpDeskTeamProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class logsUserAdded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(logsUserAdded));
        
        string IMigrationMetadata.Id
        {
            get { return "201804291351464_logsUserAdded"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
