// <auto-generated />
namespace HelpDeskTeamProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Invitationmodelemailchanged : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Invitationmodelemailchanged));
        
        string IMigrationMetadata.Id
        {
            get { return "201804241356433_Invitation model email changed "; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
